# Generated by Django 4.2.17 on 2025-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='purpose_of_travel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
